# Generated by Django 5.2.5 on 2025-09-06 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_rename_date_review_created_at_review_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
